### ISSUE TITLE
outdated Socket2 version

### ISSUE THREAD

**Issue by barmettlerl** [Distributed-EPFL/talk#12]
<img width="939" alt="Screenshot 2023-08-25 at 17 14 36" src="https://github.com/Distributed-EPFL/talk/assets/12638113/fd0ae041-d7d1-4319-8dca-0b0186046c72">

The function 
```
 socket.set_reuse_port(true)
```
does not exists on the socket version 0.4.4. Thus to make it work the version should be updated to version `socket2 = { version = "0.5.3" }`

**Comment by mvidigueira** [comment]
Fixed with the latest push
